import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import { UserButton } from "@/components/user-button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="p-4 flex justify-end">
          {session?.user ? (
            <UserButton user={session.user} />
          ) : (
            <a 
              href="/login"
              className="bg-black text-white font-bold py-1 px-2 rounded text-sm"
            >
              Sign in
            </a>
          )}
        </div>
        {children}
      </body>
    </html>
  );
}
